sonar.sources=backend
sonar.exclusions=tests/**,backend/core/init.sql,backend/repositories/**,backend/utils/exception_handlers.py
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12