sonar.sources=backend
sonar.exclusions=tests/**,backend/core/init.sql,backend/repositories/**,backend/utils/exception_handlers.py,backend/utils/cloud.py,backend/models.py,backend/errors.py,backend/core/engine.py,backend/dependencies/dependencies.py,backend/dependencies/annotations.py
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12