from typing import Protocol
from backend import models

class IDataRepository(Protocol):

    async def get_user_data(self, user_id: str) -> models.UserResponse: ...

    async def get_users_by_ids(self, ids: list[str]) -> models.UsersResponse: ...

    async def get_users_by_usernames(self, usernames: list[str]) -> models.UsersResponse: ...

    async def set_user_nickname(self, nickname: str, user_id: str) -> None: ...


class IChatRepository(Protocol):

    async def get_user_chats(self, user_id: str) -> set[str]: ...

    async def add_chat(self, permissions: dict) -> str: ...

    async def set_chat(self, message: models.MessageModel) -> None: ...

    async def get_chat_by_id(self, chat_id: str) -> models.ChatModel: ...


class IAuthRepository(Protocol):

    async def register_new(self, username: str, email: str, password: str) -> str: ...

    async def check_user(self, username: str) -> models.UsersBase: ...

    async def auth_user(self, username: str, password: str) -> str: ...


class IMessagesRepository(Protocol):

    async def add_message(self, messages: models.MessageModel) -> None: ...

    async def get_messages_by_chat(self, chat_id: str, limit: int, offset: int) -> models.MessagesResponse: ...

class IPasswordEncrypter(Protocol):

    async def encrypt_password(self, password: str) -> str: ...

    async def validate_password(self, password: str, hashed: str) -> bool: ...

class IBlacklistRepository(Protocol):

    async def unvalidate_token(self, token: str, live_time: int) -> None: ...

    async def check_blacklist(self, token: str) -> bool: ...

class IAvatarLoader(Protocol):

    async def load_avatar(self, avatar: bytes, user_id: str) -> None: ...

    async def set_default_avatar(self, user_id: str) -> None: ...

class IIdGenerator(Protocol):

    async def generate_userid(self) -> int: ...

    def generate_chatid(self, users: list[int]) -> int: ...

class ISockManager(Protocol):

    async def new_chat(self, chat: models.ChatModel) -> None: ...

class IKeyRepository(Protocol):

    async def add_prekeys(self, user_id: str, keys: list[str]) -> None: ...

    async def get_prekey(self, user_id: str) -> str: ...

    async def update_signed_key(self, user_id: str, signed_key: str) -> None: ...

    async def get_user_keys(self, user_id: str) -> models.UserKeysResponse: ...