from typing import Protocol
from backend import models
from io import BytesIO

class IDataRepository(Protocol):

    async def get_user_data(self, user_id: int) -> models.UserResponse: ...

    async def get_users_by_ids(self, ids: list[int]) -> models.UsersResponse: ...

    async def get_users_by_usernames(self, usernames: list[str]) -> models.UsersResponse: ...

    async def set_user_avatar(self, avatar: BytesIO, user_id: int) -> None: ...


class IChatRepository(Protocol):

    async def get_user_chats(self, user_id: int) -> list[int]: ...

    async def add_chat(self, permissions: dict) -> str: ...

    async def set_chat(self, message: models.MessageModel) -> None: ...


class IAuthRepository(Protocol):

    async def register_new(self, username: str, email: str, password: str) -> int: ...

    async def check_user(self, username: str) -> models.usersBase: ...

    async def auth_user(self, username: str, password: str) -> int: ...


class IMessagesRepository(Protocol):

    async def add_message(self, messages: models.MessageModel) -> None: ...

    async def get_messages_by_chat(self, chat_id: str, limit: int, offset: int) -> models.MessagesResponse: ...

class IPasswordEncrypter(Protocol):

    async def encrypt_password(self, password: str) -> str: ...

    async def validate_password(self, password: str, hashed: str) -> bool: ...

class IBlacklistRepository(Protocol):

    async def unvalidate_token(self, token: str, live_time: int) -> None: ...

    async def check_blacklist(self, token: str) -> bool: ...

class IAvatarLoader(Protocol):

    async def load_avatar(self, avatar: bytes, user_id: int) -> str: ...

    async def set_default_avatar(self, user_id: int) -> None: ...